name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install Java & Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk zip unzip

    - name: Install Build Tools
      run: |
        pip install buildozer==1.5.0
        buildozer android clean

    - name: Build APK
      run: |
        buildozer -v android release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sms-app
        path: bin/*.apk
